version: 2

jobs:
    build:
        docker:
            - image: circleci/node:6.10.3
            - image: mdillon/postgis:9.6
              environment:
                - POSTGRES_USER=postgres
                - POSTGRES_DB=pt_test

        steps:
            - run:
                name: "Install Yarn PPAs"
                command: "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && echo 'deb https://dl.yarnpkg.com/debian/ stable main' | sudo tee /etc/apt/sources.list.d/yarn.list"
            - run:
                name: "Update APT Cache & Install latest yarn"
                command: "sudo apt-get -y update && sudo apt-get install -y yarn && service postgresql start"
            - run:
                name: "Locked NPM Version"
                command: "source ~/.bashrc && nvm install 6.10.2 && nvm use 6.10.2 && nvm alias default 6.10.2"

            - checkout

            - run:
                name: "yarn install"
                command: "source ~/.bashrc && yarn install"
            - run:
                name: "yarn lint"
                command: "source ~/.bashrc && yarn run lint"
            - run:
                name: "yarn doc"
                command: "source ~/.bashrc && yarn run doc"
            - run:
                name: "yarn pretest"
                command: "source ~/.bashrc && yarn run pretest"
            - run:
                name: "yarn run coverage"
                command: "source ~/.bashrc && yarn run coverage"
                no_output_timeout: 12000
